"""empty message

Revision ID: 3bd7144b0ddc
Revises: f41755322dc8
Create Date: 2020-03-09 16:00:29.063149

"""
from datetime import datetime
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3bd7144b0ddc"
down_revision = "f41755322dc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"INSERT INTO sizes values ('{uuid4()}', '{datetime.utcnow()}', null, 1, 'pequeno', 10.00, '00:05:00'), ('{uuid4()}', '{datetime.utcnow()}', null, 2, 'médio', 13.00, '00:07:00'),('{uuid4()}', '{datetime.utcnow()}', null,3, 'grande', 15.00, '00:10:00')"
    )
    op.execute(
        f"INSERT INTO flavors values ('{uuid4()}', '{datetime.utcnow()}', null, 1, 'morango', '00:00:00'), ('{uuid4()}', '{datetime.utcnow()}', null, 2, 'banana', '00:00:00'),('{uuid4()}', '{datetime.utcnow()}', null,3, 'kiwi', '00:03:00')"
    )
    op.execute(
        f"INSERT INTO customizations values ('{uuid4()}', '{datetime.utcnow()}', null, 1, 'granola', 0.00, '00:00:00'), ('{uuid4()}', '{datetime.utcnow()}', null, 2, 'paçoca', 3.00, '00:03:00'),('{uuid4()}', '{datetime.utcnow()}', null,3, 'leite ninho', 3.00, '00:00:00')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DELETE from  sizes")
    op.execute(f"DELETE from  flavors")
    op.execute(f"DELETE from  customizations")
    # ### end Alembic commands ###
