# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discounts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import symbol_database as _symbol_database
from src.discountsgrpc import domains_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='discounts.proto',
    package='discountsgrpc',
    syntax='proto3',
    serialized_options=b'H\001ZVgithub.com/dalmarcogd/mobstore/products/internal/discounts/discountsgrpc;discountsgrpc',
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0f\x64iscounts.proto\x12\rdiscountsgrpc\x1a\rdomains.proto2I\n\tDiscounts\x12<\n\x03Get\x12\x18.domains.DiscountRequest\x1a\x19.domains.DiscountResponse\"\x00\x42ZH\x01ZVgithub.com/dalmarcogd/mobstore/products/internal/discounts/discountsgrpc;discountsgrpcb\x06proto3'
    ,
    dependencies=[domains_pb2.DESCRIPTOR, ])

_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DESCRIPTOR._options = None

_DISCOUNTS = _descriptor.ServiceDescriptor(
    name='Discounts',
    full_name='discountsgrpc.Discounts',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=49,
    serialized_end=122,
    methods=[
        _descriptor.MethodDescriptor(
            name='Get',
            full_name='discountsgrpc.Discounts.Get',
            index=0,
            containing_service=None,
            input_type=domains_pb2._DISCOUNTREQUEST,
            output_type=domains_pb2._DISCOUNTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_DISCOUNTS)

DESCRIPTOR.services_by_name['Discounts'] = _DISCOUNTS

# @@protoc_insertion_point(module_scope)
