# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domains.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='domains.proto',
  package='domains',
  syntax='proto3',
  serialized_options=b'H\001ZPgithub.com/dalmarcogd/mobstore/products/internal/domains/domainsgrpc;domainsgrpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdomains.proto\x12\x07\x64omains\"6\n\x0f\x44iscountRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"c\n\x10\x44iscountResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\npercentage\x18\x03 \x01(\x02\x12\x16\n\x0evalue_in_cents\x18\x04 \x01(\x02\x42TH\x01ZPgithub.com/dalmarcogd/mobstore/products/internal/domains/domainsgrpc;domainsgrpcb\x06proto3'
)




_DISCOUNTREQUEST = _descriptor.Descriptor(
  name='DiscountRequest',
  full_name='domains.DiscountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='domains.DiscountRequest.product_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='domains.DiscountRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=80,
)


_DISCOUNTRESPONSE = _descriptor.Descriptor(
  name='DiscountResponse',
  full_name='domains.DiscountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='domains.DiscountResponse.product_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='domains.DiscountResponse.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percentage', full_name='domains.DiscountResponse.percentage', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_in_cents', full_name='domains.DiscountResponse.value_in_cents', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['DiscountRequest'] = _DISCOUNTREQUEST
DESCRIPTOR.message_types_by_name['DiscountResponse'] = _DISCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscountRequest = _reflection.GeneratedProtocolMessageType('DiscountRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCOUNTREQUEST,
  '__module__' : 'domains_pb2'
  # @@protoc_insertion_point(class_scope:domains.DiscountRequest)
  })
_sym_db.RegisterMessage(DiscountRequest)

DiscountResponse = _reflection.GeneratedProtocolMessageType('DiscountResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISCOUNTRESPONSE,
  '__module__' : 'domains_pb2'
  # @@protoc_insertion_point(class_scope:domains.DiscountResponse)
  })
_sym_db.RegisterMessage(DiscountResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
