// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package discountsgrpc

import (
	context "context"
	domainsgrpc "github.com/dalmarcogd/mobstore/products/internal/domains/domainsgrpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DiscountsClient is the client API for Discounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscountsClient interface {
	Get(ctx context.Context, in *domainsgrpc.DiscountRequest, opts ...grpc.CallOption) (*domainsgrpc.DiscountResponse, error)
}

type discountsClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscountsClient(cc grpc.ClientConnInterface) DiscountsClient {
	return &discountsClient{cc}
}

var discountsGetStreamDesc = &grpc.StreamDesc{
	StreamName: "Get",
}

func (c *discountsClient) Get(ctx context.Context, in *domainsgrpc.DiscountRequest, opts ...grpc.CallOption) (*domainsgrpc.DiscountResponse, error) {
	out := new(domainsgrpc.DiscountResponse)
	err := c.cc.Invoke(ctx, "/discountsgrpc.Discounts/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountsService is the service API for Discounts service.
// Fields should be assigned to their respective handler implementations only before
// RegisterDiscountsService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type DiscountsService struct {
	Get func(context.Context, *domainsgrpc.DiscountRequest) (*domainsgrpc.DiscountResponse, error)
}

func (s *DiscountsService) get(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domainsgrpc.DiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/discountsgrpc.Discounts/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Get(ctx, req.(*domainsgrpc.DiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterDiscountsService registers a service implementation with a gRPC server.
func RegisterDiscountsService(s grpc.ServiceRegistrar, srv *DiscountsService) {
	srvCopy := *srv
	if srvCopy.Get == nil {
		srvCopy.Get = func(context.Context, *domainsgrpc.DiscountRequest) (*domainsgrpc.DiscountResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "discountsgrpc.Discounts",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Get",
				Handler:    srvCopy.get,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "discounts.proto",
	}

	s.RegisterService(&sd, nil)
}
